mod texture_handle;
pub mod atlas;

use wgpu::wgt::TextureDescriptor;
use crate::constants;
use crate::util::auto_generated_id::AutoGeneratedId;
use crate::util::image_utils::ImageData;

#[derive(Debug)]
pub struct ImageTooBigError {
    image_size: (u32, u32)
}

impl std::fmt::Display for ImageTooBigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "The image size {:?} is too big to fit in a texture, the maximum size is {}", self.image_size, constants::TEXTURE_MAX_SIZE)
    }
}

impl std::error::Error for ImageTooBigError { }

#[derive(Debug)]
pub struct WrongTextureSizeError {
    texture_size: (u32, u32),
    image_size: (u32, u32)
}

impl WrongTextureSizeError {
    pub fn new(texture_size: (u32, u32), image_size: (u32, u32)) -> Self {
        Self { texture_size, image_size }
    }
}

impl std::fmt::Display for WrongTextureSizeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "The texture size {:?} and image size {:?} don't match", self.texture_size, self.image_size)
    }
}

impl std::error::Error for WrongTextureSizeError { }

pub type TexId = AutoGeneratedId<Tex>;

#[derive(Clone)]
pub struct Tex {
    id: TexId,
    width: u32,
    height: u32,
    wgpu_texture: wgpu::TextureView,
    wgpu_read_buffer: wgpu::Buffer,
    wgpu_write_buffer: wgpu::Buffer
}

impl Tex {
    pub fn new(device: &wgpu::Device, queue: &wgpu::Queue, image_data: &ImageData) -> Result<Self, ImageTooBigError> {
        if image_data.width() > constants::TEXTURE_MAX_SIZE as u32 || image_data.height() > constants::TEXTURE_MAX_SIZE as u32 {
            return Err(ImageTooBigError { image_size: (image_data.width(), image_data.height()) });    
        }
        
        let id = TexId::new();
        let byte_size = Self::padded_row_bytes(image_data.width()) * image_data.height() as usize;

        let wgpu_read_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some(&format!("texture ({:?}) read buffer", id)),
            size: byte_size as wgpu::BufferAddress,
            usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
            mapped_at_creation: false,
        });

        let wgpu_write_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some(&format!("texture ({:?}) write buffer", id)),
            size: byte_size as wgpu::BufferAddress,
            usage: wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let size = wgpu::Extent3d {
            width: image_data.width(),
            height: image_data.height(),
            depth_or_array_layers: 1,
        };

        let wgpu_texture = device.create_texture(&TextureDescriptor {
            label: Some(&format!("texture ({:?})", id)),
            size,
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rgba8UnormSrgb,
            usage: wgpu::TextureUsages::COPY_SRC | wgpu::TextureUsages::COPY_DST | wgpu::TextureUsages::TEXTURE_BINDING,
            view_formats: &[]
        });

        let wgpu_texture: wgpu::TextureView = wgpu_texture.create_view(&wgpu::TextureViewDescriptor::default());

        let result = Self {
            id,
            width: image_data.width(),
            height: image_data.height(),
            wgpu_texture,
            wgpu_read_buffer,
            wgpu_write_buffer,
        };

        result.replace_content(device, queue, image_data).expect("Texture and image have the same size");

        Ok(result)
    }

    pub fn id(&self) -> TexId {
        self.id
    }

    pub fn width(&self) -> u32 {
        self.width
    }

    pub fn height(&self) -> u32 {
        self.height
    }

    pub fn wgpu_texture(&self) -> &wgpu::TextureView {
        &self.wgpu_texture
    }

    pub fn texture_content(&self, device: &wgpu::Device, queue: &wgpu::Queue) -> Vec<u8> {
        Self::load_read_buffer(device, queue, &self.wgpu_read_buffer, self.wgpu_texture.texture(), self.width, self.height);
        Self::extract_from_read_buffer(device, &self.wgpu_read_buffer, self.width, self.height)
    }

    pub fn replace_content(&self, device: &wgpu::Device, queue: &wgpu::Queue, image: &ImageData) -> Result<(), WrongTextureSizeError> {
        if self.width != image.width() || self.height != image.height() {
            return Err(WrongTextureSizeError::new((self.width, self.height), (image.width(), image.height())));
        }

        Self::load_write_buffer(queue, &self.wgpu_write_buffer, image.data(), image.width(), image.height());
        Self::copy_write_buffer_to_texture(
            device,
            queue,
            &self.wgpu_write_buffer,
            self.wgpu_texture.texture(),
            image.width(),
            image.height()
        );

        Ok(())
    }

    fn load_read_buffer(
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        read_buffer: &wgpu::Buffer,
        texture: &wgpu::Texture,
        width: u32,
        height: u32
    ) {
        let padded_row_bytes = Self::padded_row_bytes(width);

        let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("Texture to Buffer Copy Encoder"),
        });

        encoder.copy_texture_to_buffer(
            wgpu::TexelCopyTextureInfo {
                texture,
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
            },
            wgpu::TexelCopyBufferInfo {
                buffer: read_buffer,
                layout: wgpu::TexelCopyBufferLayout {
                    offset: 0,
                    bytes_per_row: Some(padded_row_bytes as u32),
                    rows_per_image: Some(height),
                },
            },
            wgpu::Extent3d {
                width,
                height,
                depth_or_array_layers: 1,
            },
        );

        queue.submit(std::iter::once(encoder.finish()));
    }

    fn map_buffer(device: &wgpu::Device, buffer_slice: &wgpu::BufferSlice) {
        let (tx, rx) = std::sync::mpsc::channel();
        buffer_slice.map_async(wgpu::MapMode::Read, move |result| {
            tx.send(result).unwrap();
        });

        device.poll(wgpu::PollType::wait_indefinitely()).unwrap();
        rx.recv().unwrap().unwrap();
    }

    fn extract_from_read_buffer(device: &wgpu::Device, read_buffer: &wgpu::Buffer, width: u32, height: u32) -> Vec<u8> {
        let slice = read_buffer.slice(..);
        Self::map_buffer(device, &slice);

        let mut data = {
            let mapped_range = slice.get_mapped_range().unwrap();
            mapped_range.to_vec()
        };

        read_buffer.unmap();

        let row_bytes = (width * 4) as usize;
        let padded_row_bytes = Self::padded_row_bytes(width);

        if row_bytes == padded_row_bytes {
            data
        } else {
            let mut offset = 0;
            for _ in 0..height {
                data.drain((offset + row_bytes)..(offset + padded_row_bytes));
                offset += row_bytes;
            }

            data
        }
    }

    fn load_write_buffer(
        queue: &wgpu::Queue,
        write_buffer: &wgpu::Buffer,
        data: &[u8],
        width: u32,
        height: u32
    ) {
        let row_bytes = (width * 4) as usize;
        let padded_row_bytes = Self::padded_row_bytes(width);

        if row_bytes == padded_row_bytes {
            queue.write_buffer(write_buffer, 0, data);
        } else {
            let missing_bytes = padded_row_bytes - row_bytes;

            let mut padded_data = Vec::new();

            let mut offset = 0;
            for _ in 0..height {
                padded_data.extend_from_slice(&data[offset..(offset + row_bytes)]);
                padded_data.extend_from_slice(&vec![0; missing_bytes]);
                offset += row_bytes;
            }

            queue.write_buffer(write_buffer, 0, &padded_data);
        }
    }

    fn copy_write_buffer_to_texture(
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        write_buffer: &wgpu::Buffer,
        texture: &wgpu::Texture,
        width: u32,
        height: u32
    ) {
        let padded_row_bytes = Self::padded_row_bytes(width);

        let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("Buffer to Texture Copy Encoder"),
        });

        encoder.copy_buffer_to_texture(
            wgpu::TexelCopyBufferInfo {
                buffer: write_buffer,
                layout: wgpu::TexelCopyBufferLayout {
                    offset: 0,
                    bytes_per_row: Some(padded_row_bytes as u32),
                    rows_per_image: Some(height),
                },
            },
            wgpu::TexelCopyTextureInfo {
                texture,
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
            },
            wgpu::Extent3d {
                width,
                height,
                depth_or_array_layers: 1
            },
        );

        queue.submit(std::iter::once(encoder.finish()));
    }

    fn padded_row_bytes(width: u32) -> usize {
        const ALIGNMENT: u32 = constants::TEXTURE_ROW_ALIGNMENT_BYTES;
        ((width * 4).div_ceil(ALIGNMENT) * ALIGNMENT) as usize
    }
}