use std::cell::RefCell;
use std::rc::Rc;
use crate::graphics::texture::uv_rect::UVRect;
use crate::util::auto_generated_id::AutoGeneratedId;

#[derive(Debug)]
pub struct TileCantFitInAtlasError;

impl std::fmt::Display for TileCantFitInAtlasError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "The tile can't fit in the atlas")
    }
}

impl std::error::Error for TileCantFitInAtlasError { }

pub type TexId = AutoGeneratedId<Tex>;

#[derive(Clone)]
pub struct Tex {
    id: TexId,
    width: u32,
    height: u32,
    wgpu_texture: wgpu::TextureView,
}

impl Tex {
    pub fn new(device: &wgpu::Device, queue: &wgpu::Queue, data: &[u8], width: u32, height: u32) -> Self {
        use wgpu::util::DeviceExt;

        let size = wgpu::Extent3d {
            width,
            height,
            depth_or_array_layers: 1,
        };

        let texture = device.create_texture_with_data(
            queue,
            &wgpu::TextureDescriptor {
                label: None,
                size,
                mip_level_count: 1,
                sample_count: 1,
                dimension: wgpu::TextureDimension::D2,
                format: wgpu::TextureFormat::Rgba8UnormSrgb,
                usage: wgpu::TextureUsages::COPY_SRC | wgpu::TextureUsages::COPY_DST | wgpu::TextureUsages::TEXTURE_BINDING,
                view_formats: &[],
            },
            wgpu::util::TextureDataOrder::LayerMajor,
            data
        );

        let texture_view: wgpu::TextureView = texture.create_view(&wgpu::TextureViewDescriptor::default());

        Self {
            id: TexId::new(),
            width,
            height,
            wgpu_texture: texture_view
        }
    }

    pub fn id(&self) -> TexId {
        self.id
    }

    pub fn width(&self) -> u32 {
        self.width
    }

    pub fn height(&self) -> u32 {
        self.height
    }

    pub fn wgpu_texture(&self) -> &wgpu::TextureView {
        &self.wgpu_texture
    }

    pub fn copy_to_buffer(&self, device: &wgpu::Device, queue: &wgpu::Queue, buffer: &wgpu::Buffer) {
        if self.width % 256 != 0 || self.height % 256 != 0 {
            panic!("The dimensions of a texture to be copied to a buffer must be multiples of 256");
        }

        let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("Texture to Buffer Copy Encoder"),
        });

        encoder.copy_texture_to_buffer(
            wgpu::TexelCopyTextureInfo {
                texture: self.wgpu_texture.texture(),
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
            },
            wgpu::TexelCopyBufferInfo {
                buffer,
                layout: wgpu::TexelCopyBufferLayout {
                    offset: 0,
                    bytes_per_row: Some(self.width * 4),
                    rows_per_image: Some(self.height),
                },
            },
            wgpu::Extent3d {
                width: self.width,
                height: self.height,
                depth_or_array_layers: 1,
            },
        );

        queue.submit(std::iter::once(encoder.finish()));
    }
}

#[derive(Clone)]
struct TexHandleData {
    texture: Tex,
    uv_rect: UVRect,
    is_valid: bool
}

#[derive(Clone)]
pub struct TexHandle {
    data: Rc<RefCell<TexHandleData>>
}

impl TexHandle {
    pub fn snapshot(&self) -> (Tex, UVRect) {
        let data = self.data.borrow();
        (data.texture.clone(), data.uv_rect)
    }
}

pub struct TexAtl {
    device: wgpu::Device,
    queue: wgpu::Queue,
    texture: Tex,
    tiles: Vec<TexHandle>
}

impl TexAtl {
    fn new(device: &wgpu::Device, queue: &wgpu::Queue) -> Self {
        let texture = Tex::new(device, queue, &[0u8], 1, 1);

        Self {
            device: device.clone(),
            queue: queue.clone(),
            texture,
            tiles: vec![]
        }
    }

    fn add_tile(&mut self, data: &[u8], width: u32, height: u32) -> Result<TexHandle, TileCantFitInAtlasError> {




        Ok(TexHandle {})
    }

    fn add_tiles(&mut self, tiles: &[()]) -> Result<Vec<TexHandle>, ()> {
        Ok(vec![TexHandle {}])
    }

    fn remove_tile(&mut self, tex_handle: TexHandle) {

    }

    fn remove_tiles(&mut self, tex_handles: &[TexHandle]) {

    }

    fn pack(&mut self) {

    }
}