use std::cell::RefCell;
use std::rc::Rc;
use crate::graphics::tex::Tex;
use crate::graphics::texture::uv_rect::UVRect;
use crate::util::auto_generated_id::AutoGeneratedId;

#[derive(Clone)]
struct TexHandleData {
    texture: Tex,
    uv_rect: UVRect,
    is_valid: bool
}

#[derive(Clone)]
pub struct TexHandle {
    id: AutoGeneratedId<Self>,
    data: Rc<RefCell<TexHandleData>>
}

impl TexHandle {
    pub fn new(texture: Tex, uv_rect: UVRect) -> Self {
        Self {
            id: AutoGeneratedId::new(),
            data: Rc::new(RefCell::new(TexHandleData { texture, uv_rect, is_valid: false }))
        }
    }

    pub fn update(&self, texture: Tex, uv_rect: UVRect) {
        let mut data = self.data.borrow_mut();
        data.texture = texture;
        data.uv_rect = uv_rect;
    }

    pub fn id(&self) -> AutoGeneratedId<Self> {
        self.id
    }
    
    pub fn snapshot(&self) -> (AutoGeneratedId<Self>, Tex, UVRect, bool) {
        let data = self.data.borrow();
        (self.id, data.texture.clone(), data.uv_rect, data.is_valid)
    }

    pub fn invalidate(&self) {
        self.data.borrow_mut().is_valid = false;
    }
}