use crate::auto_generated_id::AutoGeneratedId;
use crate::renderer::texture::uv_rect::UVRect;
use crate::renderer::texture::x::Tex;

pub type TextureHandleId = AutoGeneratedId<TextureHandle>;

pub struct TextureHandle {
    id: TextureHandleId,
    texture: Tex,
    uv_rect: UVRect
}

impl TextureHandle {
    pub fn new(texture: &Tex, uv_rect: UVRect) -> Self {
        Self {
            id: TextureHandleId::new(),
            texture: texture.clone(),
            uv_rect,
        }
    }
    
    pub fn id(&self) -> TextureHandleId {
        self.id
    }
    
    pub fn texture(&self) -> &Tex {
        &self.texture
    }
    
    pub fn uv_rect(&self) -> UVRect {
        self.uv_rect
    }
}