use crate::renderer::texture::Texture;
use crate::renderer::texture::uv_rect::UVRect;
use crate::util::auto_generated_id::AutoGeneratedId;

pub type TextureHandleId = AutoGeneratedId<TextureHandle>;

#[derive(Clone, Debug)]
pub struct TextureHandle {
    id: TextureHandleId,
    texture: Texture,
    uv_rect: UVRect
}

impl TextureHandle {
    pub fn new(texture: &Texture, uv_rect: UVRect) -> Self {
        Self {
            id: TextureHandleId::new(),
            texture: texture.clone(),
            uv_rect,
        }
    }
    
    pub fn id(&self) -> TextureHandleId {
        self.id
    }
    
    pub fn texture(&self) -> &Texture {
        &self.texture
    }
    
    pub fn uv_rect(&self) -> UVRect {
        self.uv_rect
    }
}