pub mod texture_handle;
pub mod uv_rect;
pub mod texture_atlas;

use crate::util::auto_generated_id::AutoGeneratedId;

pub type TextureId = AutoGeneratedId<Texture>;

#[derive(Clone, Debug)]
pub struct Texture {
    id: TextureId,
    wgpu_texture: wgpu::TextureView
}

impl Texture {
    pub fn new(device: &wgpu::Device, queue: &wgpu::Queue, data: &[u8], width: u32, height: u32) -> Self {
        use wgpu::util::DeviceExt;

        let size = wgpu::Extent3d {
            width,
            height,
            depth_or_array_layers: 1,
        };

        let texture = device.create_texture_with_data(
            queue,
            &wgpu::TextureDescriptor {
                label: None,
                size,
                mip_level_count: 1,
                sample_count: 1,
                dimension: wgpu::TextureDimension::D2,
                format: wgpu::TextureFormat::Rgba8UnormSrgb,
                usage: wgpu::TextureUsages::COPY_DST | wgpu::TextureUsages::TEXTURE_BINDING,
                view_formats: &[],
            },
            wgpu::util::TextureDataOrder::LayerMajor,
            data
        );

        let texture_view: wgpu::TextureView = texture.create_view(&wgpu::TextureViewDescriptor::default());

        Self {
            id: TextureId::new(),
            wgpu_texture: texture_view,
        }
    }

    pub fn id(&self) -> TextureId {
        self.id
    }

    pub fn wgpu_texture(&self) -> &wgpu::TextureView {
        &self.wgpu_texture
    }
}