use std::cell::Cell;
use std::marker::PhantomData;

pub struct AutoGeneratedId<T> {
    id: u32,
    _marker: PhantomData<T>,
}

impl<T> AutoGeneratedId<T> {
    pub fn new() -> Self {
        thread_local! {
            static NEXT_ID: Cell<u32> = Cell::new(0);
        }

        let id = NEXT_ID.with(|next_id| {
            let id = next_id.get();
            next_id.set(id + 1);
            id
        });

        Self { id, _marker: PhantomData }
    }
}

impl<T> Copy for AutoGeneratedId<T> { }

impl<T> Clone for AutoGeneratedId<T> {
    fn clone(&self) -> Self { *self }
}

impl<T> PartialEq for AutoGeneratedId<T> {
    fn eq(&self, other: &Self) -> bool { self.id == other.id }
}

impl<T> Eq for AutoGeneratedId<T> { }

impl<T> std::hash::Hash for AutoGeneratedId<T> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state)
    }
}

impl<T> std::fmt::Debug for AutoGeneratedId<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "AutoGeneratedId({})", self.id)
    }
}

impl<T> PartialOrd for AutoGeneratedId<T> {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl<T> Ord for AutoGeneratedId<T> {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.id.cmp(&other.id)
    }
}